version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: ./compose/local/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: /start
    env_file:
      - .env
